### PR TITLE
#1 tri.txt implemented

### PR DESCRIPTION
**Pull request by romansvozil**
#1 resolved

### CODE REVIEW

**Review by Wunson — CHANGES_REQUESTED** [review]
your implementation is clean but not correct. according to http://www.predskolaci.cz/varila-mysicka-kasicku-na-zelenem-rendlicku/9940. fix the first line from 25th character

**Comment by romansvozil** [comment]
Oh, mb, I'll try to fix it tonight. Thanks for your review! 👍

**Comment by thejoeejoee** [comment]
guys I have no idea what is going on here :rofl: but please continue, you're really making my day :mechanical_arm:

**Review by Wunson — APPROVED** [review]
wow i didnt expect you to add all the lines. tihis is excelent work. approved

**Comment by romansvozil** [comment]
Thanks for your approval sir! @Wunson

**Comment by Wunson** [comment]
the project manager should be at work today. i hope he will take a look and approve it as well

**Pull request merged**
